### ISSUE TITLE
Keep submenu opened when navigating between pages

### ISSUE THREAD

**Issue by apod42** [FrDH/jQuery.mmenu#493]
Hello,

Very happy with mmenu for almost a year now. But I was wandering if it is possible to keep an opened submenu this way (opened) when the user navigates between pages. Please see explanation below:

Actual behavior:

1. User opens mmenu on page-one.html
2. User opens a submenu in mmenu (clicks on the arrow)
3. User closes mmenu
4. User opens mmenu again (the submenu is still opened, just as the user left it) and goes to page-two.html
5. Now, on page-two.html user opens mmenu but the submenu he previously opened is closed.

Desired behavior:

1. same
2. same
3. same
4. same
5. Now, on page-two.html user opens mmenu and the submenu he previously opened is STILL OPENED just as user left it.

**Comment by FrDH** [comment]
IMHO, that would feel odd for the user. On a desktop website, you don't have a menu item "selected" just because the user hovered over it before visiting a different page.

That being said, I think you could achieve this behavior with HTML5 [local storage](http://www.w3schools.com/html/html5_webstorage.asp) and the `openPanel` method in the [mmenu API](http://mmenu.frebsite.nl/documentation/api.html).

**Comment by apod42** [comment]
Thinking of it again now, yes, you are right - it would feel odd. Please close this issue...
