### ISSUE TITLE
Gap appears when closing a zposition:next off-canvas menu in Firefox

### ISSUE THREAD

**Issue by jonathanmelville** [FrDH/jQuery.mmenu#496]
In Firefox, when closing an off-canvas menu that uses the zposition:next option (so the menu sits right next to the page), a large gap appears when closing the menu.

This seems to be triggered if any elements on the main page have padding applied.

The main page and the off-canvas menu seem to be animating at different times and one looks like it gets ahead of the other, which causes this gap.

Below is a screenshot of a menu in the process of closing. Notice the gap that forms. 

![screen shot 2016-01-03 at 7 27 00 pm](https://cloud.githubusercontent.com/assets/7415693/12081728/0a04dbe4-b251-11e5-9108-c3a3bbd847d5.png)

**Comment by xstortionist** [comment]
+1 - I just made the same issue earlier this morning. Been trying all day to fix the issue with no luck.

**Comment by jonathanmelville** [comment]
@xstortionist I've been doing the same thing. Would love to know if you find a fix.

I've noticed that it's only triggered when elements in the main body have padding. So that kinda sucks seeing as how you're probably going to need to apply some padding at some point...

**Comment by xstortionist** [comment]
@jonathanmelville I've had no luck and I'm currently trying out Mango Slideout for my needs. I love mmenu but it's a bit over whelming and a bit much for what I simply need it for.

**Comment by FrDH** [comment]
The problem probably is with the page and menu being animated separately. Though the animation (CSS transition) is triggered at exactly the same time, the HTML nodes are not somehow "linked" together so a small gap might appear.
I've been thinking about removing the "next" value because of this issue, but have kept it since nobody complained before :)

IMHO, you're better off using the "effect-menu-slide" extension in combination with having the menu behind the page (as seen on mmenu.frebsite.nl).

**Comment by xstortionist** [comment]
Just tested and on my 4K monitor, there is still a visible gap when animating the fixed header. On my regular non-4k monitor, the issue is not as persistent and visible.

**Comment by jonathanmelville** [comment]
After playing around some more, I've found that setting the color of the <body> tag to be the same as the background color of the menu panel disguises this glitch pretty well.

Please keep this option available, it performs as expected on webkit.
