### ISSUE TITLE
After added fixedElements for my navbar, the navbar goes to the bottom

### ISSUE THREAD

**Issue by bardtian** [FrDH/jQuery.mmenu#500]
Mmenu was working fine in this page without fixedElements.
http://demos.bardtn.com/md1/page.html

After I added fixedElements, it works like this:
http://demos.bardtn.com/md1/pagef.html

Did I miss something?

**Comment by FrDH** [comment]
The "fixedElements" add-on provides a workaround for elements with `position: fixed;` that are inside the "page". Basically, all it does is move these elements out of the page because of this "bug":
https://coderwall.com/p/ka0low/don-t-mix-position-fixed-with-css-transforms

I guess that messes up your CSS.

If it works better w/o the add-on, don't use it :)
