### ISSUE TITLE
Completely Kills AdSense Ads

### ISSUE THREAD

**Issue by mikekberg** [FrDH/jQuery.mmenu#501]
For some reason when you use this plugin all Google AdSense ad's iframes are emptied out. we've lost quite a bit of revenue until we found the bug. Once this component is removed Ad Sense Ad's start loading again.

**Comment by FrDH** [comment]
This is probably due to the plugin wrapping all HTML in one DIV (and so actaully re-inserting your ads into the DOM). 
As adviced by the tutorial, you are best off wrapping all HTML in one DIV by default, that way the plugin doesn't need to do that. 

If for some reason you can't wrap all HTML in one DIV, for example because a tooltip plugin adds DIVs to the BODU, you could always tell the plugin what DIV it should consider to be the page using the `offCanvas.pageSelector` configuration option.

One last option (I personally would advcice against using), is to set the `offCanvas.wrapPageIfNeeded` configuration option to false.

Hope this helps.

**Comment by mikekberg** [comment]
I've tried: 
`	    $("#mobile-menu").mmenu({
                "searchfield": true,
				offCanvas: {
					wrapPageIfNeeded: false
   				}
            });
`

and

`
	$("#mobile-menu").mmenu({
                "searchfield": true,
				offCanvas: {
					wrapPageIfNeeded: false
   				}
            });
`

Both give the same results, working on a codepen to show an example.

**Comment by FrDH** [comment]
I don't see any difference in the two.
Anyway, `offCanvas.wrapPageIfNeeded` is a configuration option, you should add it to the configuration (second) object:
````
$("#my-menu").mmenu({
    // first object: options
}, {
    // second object: configuration
});
