### ISSUE TITLE
Not compatible with boostrap v4 modals

### ISSUE THREAD

**Issue by jacargentina** [FrDH/jQuery.mmenu#518]
I've migrated my site to bootstrap v4-alpha, and the effect is that opening a modal makes the backdrop (from bootstrap) to cover the opened modal.

I've confirmed it is related to mmenu because commenting the mmenu activation, all works just fine.

Any advice?

**update:** test the behaviour on http://www.nexion.com.ar:3000, click the search button at top - right corner

**Comment by FrDH** [comment]
This is because the DIV that is considered to be the page (.mm-page) has a z-index.
I think you should be OK if you tell the plugin not to wrap all DIVs in a single DIV by specifying the "pageSelector" configuration option for the [offCanvas add-on[(http://mmenu.frebsite.nl/documentation/addons/off-canvas.html). That way, all bootstrap modals and dialogs etc are outside of the DIV that is considered to be the page.

Something like this:
````javascript
$("#my-menu").mmenu({
   // options
}, {
   // config
   offCanvas: {
      pageSelector: "#wrapper"
   }
});
````

**Comment by jacargentina** [comment]
Excelent!
