### ISSUE TITLE
mm-slideout not responsive when screen width < 550px

### ISSUE THREAD

**Issue by chungconscious** [FrDH/jQuery.mmenu#572]
I have a hamburger menu (outside of the mmenu wrapper) 
```
<a id="hamburger" class="mm-slideout" href="#my-menu">
        <span class="top-bar"></span>
        <span class="middle-bar"></span>
        <span class="bottom-bar"></span>
</a>

<div id="my-wrapper">

```

When the screen width is under 550px the hamburger is not getting pushed to the left as it should be. 

![image](https://cloud.githubusercontent.com/assets/16165145/15245371/60b146aa-1906-11e6-8344-aa8edc949647.png)

But as soon as width > 550px, it's all fine
![image](https://cloud.githubusercontent.com/assets/16165145/15245467/f3cf3af0-1906-11e6-9c4e-881cf11b6e30.png)

Alternatively, I nested it like this

```
 <div id="my-wrapper">
  <header>
    <a id="hamburger"...>
```

But then that put the mmenu overlay on TOP of the hamburger menu which meant 
1) the hamburger menu gets darkened and is under the overlay
![image](https://cloud.githubusercontent.com/assets/16165145/15245483/0ec5f66e-1907-11e6-90bb-a1e2604e74a1.png)

2) mouseover is not detected and the mouse remains a pointer instead of turning to a cursor

Please advise!

**Comment by FrDH** [comment]
I can't tell you why it would be different for smaller screens (maybe you're loading some CSS using a media-query?), but here's the guide for having fixed elements:
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html

1. Make sure you've included the "fixed-elements" add-on
2. Add the class "Fixed" to the elements that have `position: fixed`.

That should do the trick. If it doesn't, please provide an online example, otherwise there is not much I can do to help.
