### ISSUE TITLE
Reinit menu after authentication

### ISSUE THREAD

**Issue by longmd** [FrDH/jQuery.mmenu#587]
Im working on a single page app, where I have my sign in and register buttons housed within a navbar above the menu panels. Upon authentication, I want to pop that object from the navbars array, but would need to reinitialize the menu element to get the classing right for the remaining navbars. Is there a solution to this without having to do a full refresh of the browser page?

**Comment by longmd** [comment]
I guess the same thing would need to happen, only in reverse, when a user signs out. I would like to add that navbar back in...

**Comment by FrDH** [comment]
Interesting idea. Unfortunately there currently is no "reinit" method for the navbars, 
I guess the easiest solution would be to switch between a log-in and log-out button. That way everyting else can stay the same.

Assuming you're using fontawesom to create the icons:
````js
function login() {
    $("#my-button").removeClass( "fa-lock" ).addClass( "fa.unlock" );
}
function logout() {
    $("#my-button").removeClass( "fa-unlock" ).addClass( "fa.lock" );
}
````

Otherwise I gues you'd need to remove the "navbar-content-X" class from the navbar and replace it with "navbar-content-Y", where X and Y represent the amount of buttons in the navbar.

I'll see if I can come up with a more solit solution for changing the contents of a navbar.

Hope this helps.

**Comment by longmd** [comment]
Thanks for your reply. We actually have the sign out button listed in a subpanel of a user menu option that gets rendered after authenticating, so the goal is to actually have those buttons there when you're logged out, and removed completely when logged in. 

I'm thinking I'll just add a class to the menu element itself on auth and control those via CSS. Do keep us posted if you come up with something problematically in the future. 

I have another idea/question related to the init of panels which I will open up a new thread for.
