### ISSUE TITLE
add shadow-menu to shadows extension

### ISSUE THREAD

**Issue by Patta** [FrDH/jQuery.mmenu#616]
it would be nice if the offCanvas menu with "zposition: front" can have a shadow depending on the position (left, right, ...) for example via a shadow-menu extension :) thx

**Comment by FrDH** [comment]
Adding a shadow behind the menu would notably slow down the animation, even on a desktop computer.
The workaround for the `shadow-page` extension was to add a shadow in front of the menu instead of behind the page. If you look closely, you'll see the shadow does not animate with the page, it just appears after the animation.

If you want, you can simply add a shadow with CSS:
````css
.mm-menu {
   box-shadow: 0 0 10px rgba( 0,0,0, 0.5 );
}
````
