### ISSUE TITLE
Close off-canvas menu before redirecting to linked page

### ISSUE THREAD

**Issue by jmalatia** [FrDH/jQuery.mmenu#623]
Is there any way to close the off-canvas menu after clicking a link to a new page before `mmenu` sends the redirect request to the browser?

I see there is an `onClick` event with `close` and `preventDefault` options, but I don't want to screw-up the `mmenu` functionality of sub-menus.

The issue I have is after using the off-canvas menu to select a link to a new page and I am on the new page... if a user then decides to press the `Back` button to return to the previous page, the off-canvas menu is still open on the previous page.  While I can see some reasoning for the menu to still be open, I find it not very intuitive, as I feel the page is more important than the menu when returning to a previous page and having to close it is a hassle.

Any workarounds or ideas would be appreciated.

**Comment by FrDH** [comment]
There's an option `onClick.close`, quote from [the documentation](http://mmenu.frebsite.nl/documentation/options/):
> Whether or not the menu should close after clicking a link inside it.
The default value varies per link: true if the default behavior for the clicked link is prevented, false otherwise.

The next option `onClick.preventDefault`:
>  	Whether or not to prevent the default behavior for the clicked link.
The default value varies per link: true if its href is equal to or starts with a hash (#), false otherwise.

So basically, if the href is equal to or starts with "#", the default behavior is prevented and therefor the menu will close.

If you always want to close the menu after clicking a link inside it, you can just set 'onClick.close' to `true`.
