### ISSUE TITLE
Responsive Menu swap extension

### ISSUE THREAD

**Issue by nathangath** [FrDH/jQuery.mmenu#650]
Is it possible to set up a mmenu to use the "fullscreen" extension on mobile devices and the "popup" extension above a certain breakpoint?

**Comment by FrDH** [comment]
Since both are extensions (meaning they're CSS only) that is possible.
You neef to include them in the webpage with a media-query that targets the wanted screen-sizes.
Note that both extensions are included in the ".all.css" file, so you can't use that. You'll need to include all needed add-on and extension .css files that are not included in the core .css file seporately.

**Comment by FrDH** [comment]
FYI: In the next version, there'll be a responsive option for extensions (and probably some of the add-ons).
