### ISSUE TITLE
safari issue mac os & ios

### ISSUE THREAD

**Issue by ilovegalya** [FrDH/jQuery.mmenu#663]
![untitled](https://cloud.githubusercontent.com/assets/24204592/20647158/d9c4b936-b49d-11e6-811e-b2e794770d94.jpeg)
One of the menu in the examples looks different in the latest version Safari and Chrome on Mac OS

**Comment by FrDH** [comment]
I noticed it too, it appears safari does not support `height: 100%` for an element inside a `display: flex` element.
I'll see if there is some way around this bug, but for now I'd advice not to use the justifiedListview extension.

**Comment by FrDH** [comment]
Update: this issue will be fixed in the next version.

**Comment by Quentame** [comment]
Hey @FrDH !

Have you pushed your fix yet ?

Because I just forked the project and pushed mine too.

We have to use ```display: flex;``` twice, once to expand the height of the a/span to 100% and one to center the text 😉 

I've test in Safari 5 (Win7), Safari 9 (Mac OS 10.9), Firefox 54 (both), Chrome 56/46 (both).


You will hear about me, I noticed some bugs/improvements 😄 

Thanks !

PS : I pushed ```jquery.mmenu.justifiedlistview.scss``` ... but other CSS/JS files has been modified by gulp.
Should I push the 16 other modified files, or just this file ?
