### ISSUE TITLE
Low frame rates on Android Firefox

### ISSUE THREAD

**Issue by Maffyou** [FrDH/jQuery.mmenu#682]
Hi,

I've only tested this on Android (2 different devices - one old, the other relatively new) but it can be observed on the main mmenu website http://mmenu.frebsite.nl

The frame rate when closing mmenu on Firefox for Android is very low - maybe 5fps. There's also a longer delay between tapping the hamburger icon and mmenu starting to appear.

This doesn't happen at all using Chrome.

I also tested this using Firefox for Android running on ChromeOS - it worked fine, no stuttering at all.

Anyway I'd be interested in seeing if anybody else can replicate this.

Thanks in advance.

**Comment by FrDH** [comment]
Just out of curiosity, does it help if you change the z-position of the menu to "front"?
````js
$("#menu").mmenu({
   "offCanvas": {
      "zposition": "front"
   }
});
````
This way, only the menu is animated, instead of the entire page and all if its contents.


In my experience, some HTML elements and CSS properties are very CPU expensive. For example a `box-shadow` slows down the animation a lot. Same for big images, iframes, videos and stuf like that.
If this really is an issue, you could consider to remove these CSS properties and hide these HTML elements while the menu is opened:
````css
html.mm-opened #content
{
   box-shadow: none;
}
html.mm-opened #content iframe,
html.mm-opened #content img
{
   display: none;
}
````

Hope this helps.

**Comment by Maffyou** [comment]
Hi,

Thanks for the fast reply. I tried the z-position and that solved it nicely :-)

The only knock-on effect I noticed is that using the z-position trick on desktop causes a little "jump" in the page content as the scrollbar disappears. I'll have to make sure I detect and apply when the user is specifically on Firefox on a phone.

Many thanks.

**Comment by FrDH** [comment]
You could set the `offCanvas.blockUI` option to `false`. This way users can still interact with the page while the menu is opened.

**Comment by Maffyou** [comment]
Great! Many thanks for the tip.
