### ISSUE TITLE
How might we use on Wordpress and have menu options generated dynamically?

### ISSUE THREAD

**Issue by dividor** [FrDH/jQuery.mmenu#692]
Love this menu, gorgeous! 

We have hundreds of pages on Wordpress. Manually building the menu choices isn't really an option, we would need the menu to automatically generate items. In addition - for best performance - we'd want to load only the pages on the current level.

Might this be possible? 

thanks!

**Comment by FrDH** [comment]
I guess you could use the [lazy submenus add-on](http://mmenu.frebsite.nl/documentation/addons/lazy-submenus.html), but there's a bug in it (which should be fixed in the next release). Additionally, you could have a look at the [dynamic content tutorial](http://mmenu.frebsite.nl/tutorials/dynamic-content.html) and learn how to add menu items and submenus on the fly.

Hope this helps.
