### ISSUE TITLE
theme by panel

### ISSUE THREAD

**Issue by iecwebmast** [FrDH/jQuery.mmenu#750]
Is it possible to have a theme by panel?  For example, the main menu dark and the subsequent menu panels white?

**Comment by FrDH** [comment]
Not by default, but it shouldn't that hard to create a workaround.
The "themes" extension adds the class "mm-theme-dark/light/black/white" to the menu, since extensions are CSS-only, you can do this manually when opening a panel using the [API](http://mmenu.frebsite.nl/documentation/core/api.html):
````js

var $menu = $("#my-menu").mmenu({
    extensions: [ "theme-white" ]  // lets use "white" as the default theme
});

var API = $menu.data( "mmenu" );

API.bind( "openPanel:start", function( $panel ) {
    // first, lets remove all possible theme classnames from the menu
    $menu.removeClass( "mm-theme-dark mm-theme-white mm-theme-black" );

    // second, find the new theme by checking the $panel that's being opened
    // and default back to "white"
    var theme = $panel.children( "ul" ).attr( "data-theme" ) || "white";

    // last, add the theme classname to the menu
    $menu.addClass( "mm-theme-" + theme );
});
````

Note that this approach requires you to add a "data-theme" attribute to the listviews (UL):
````html
<nav id="my-menu">
    <ul>
        <li><a>Home</a></li>
        <li><a>About</a>
            <ul data-theme="black">
                <li>...</li>
            </ul>
        </li>
    </ul>
</nav>
````

Just add another data attribute if you also want to change the background color:
````html
<ul data-theme="black" data-bg="#446688">
</ul>
````
And add it in the JS:
````js
API.bind( "openPanel:start", function( $panel ) {
    var bg = $panel.children( "ul" ).attr( "data-bg" ) || "#fff";
    $menu.css( "background-color", bg );
});
````

Hope this helps.

**Comment by iecwebmast** [comment]
Thank you very much!  This works nicely.  However, I am using the option of iconPanels to show a small part of the parent panel.  The change of them is affecting both the parent and the active panel.  Is there a way to retain the parent panel theme while changing the child panel theme?  Example, parent iconbar panel black and child panel white.

**Comment by FrDH** [comment]
Unfortunately not, the CSS for all panels is bound to the menu having a classname. You could ofcourse override the CSS manually, but I normally wouldn't recommend that as it is not update-proof.
