### ISSUE TITLE
bug type tabs

### ISSUE THREAD

**Issue by systemshock89** [FrDH/jQuery.mmenu#858]
Hello!
If configuration: clone:true - all tabs unactive and not click.
version 7.0.1

**Comment by FrDH** [comment]
Could you share your JS?
My guess is, the ID attributes for the panels no longer match. In order to prevent duplicate IDs, setting `clone: true` will prepend all IDs with "mm-".
I'll see if I can get the navbar tabs (and maybe other login in the plugin) to work around this.

For now, you could link to the prefixed IDs:
````js
"content": [
   "<a href='#mm-panel-menu'>Menu</a>",
   "<a href='#mm-panel-language'>Language</a>"
]
````

Hope this helps.

**Comment by systemshock89** [comment]
It is work!
Thank you very match!
