### ISSUE TITLE
Dimming delay

### ISSUE THREAD

**Issue by agilec-paul** [FrDH/jQuery.mmenu#859]
When using dimming you have a delay between the menu animation and the dim.

What you want to happen is it starts to dim along with the menu sliding animation, but currently it only starts to dim after the menu has finished sliding out.

**Comment by FrDH** [comment]
Hi,

Unfortunately, this is not really possible without being buggy.
It would require the semi-transparent overlay to animate out of view exactly simultaneously with the page. This almost never happens due to the overlay being an empty DIV and the page having a lot of content (an empty DIV animates faster than DIV filled with content).

**Comment by agilec-paul** [comment]
Ok that makes sense, thanks!
