### ISSUE TITLE
Boostratap 4 wrapper issue

### ISSUE THREAD

**Issue by internetstyle** [FrDH/jQuery.mmenu#863]
I'm using bootstrap 4 wrapper and everything works perfectly, except for one detail:

The third level menu opens along with the second level.

What should I do to solve this? Thanks.

**Comment by FrDH** [comment]
Is there an online example of this issue?

**Comment by internetstyle** [comment]
I'll provide an example online.

**Comment by wefixit-AT** [comment]
Any news about an example? I switched to Bootstrap4 and had to realize that now mmenu is broken

**Comment by FrDH** [comment]
Mmenu should work with bs4 and the bs4 wrapper, check the documentation on the wrapper for more info.

**Comment by wini2** [comment]
I have the same problem as internetstyle.

The counter on first level is wrong (counts all children and grandchildren). When I slide to level two, it contains all entries of level two and three.

Maybee it has something to do with bootstrap-classes or other bs-attributes because mmenu works fine, if i use a ul - li without any class.
