### ISSUE TITLE
have error in active menu in query string

### ISSUE THREAD

**Issue by nazaninhesari** [FrDH/jQuery.mmenu#904]
when a link have query string it not selected by default

http://www.master.local/accounting/invoice?sale_in

why ?

**Comment by FrDH** [comment]
With the `setSelected.current` option set to `true`, the URL you specified should highlight the`<li />` that links to "http://www.master.local/accounting/invoice". Or at least, that is how it was intended, the query string is (or should be) ignored by design.

If you want full control over what item should be highlighted, you can always add the classname specified in the `classnames.selected` configuration option ("Selected" by default) to the `<li />` manually.
Check out [this tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/styling-lists.html) on how to do so.

Hope this helps.
